baseURL = 'https://photo.moquillon.fr/'
languageCode = 'fr-FR'
defaultContentLanguage = 'fr'
title = 'Miguel Moquillon'
description = 'Photographe'
theme = 'ananke'

[languages]
  [languages.en]
    contentDir = 'content/en'
    copyright = 'Miguel Moquillon. All rights reserved'

  [languages.fr]
    contentDir = 'content/fr'
    copyright = 'Miguel Moquillon. Tous droits réservés'

enableRobotsTXT = true
#disqusShortname = 'miguel-moquillon-photoblog'

[sitemap]
changefreq = 'monthly'
priority = 0.5
filename = 'sitemap.xml'

[params]
custom_css = ['custom.css']
date_format = ':date_long'

    

